# Generated by Django 3.0 on 2022-07-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20220718_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mark',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
